name: Build QMK firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  update_and_build:
    name: Build QMK firmware
    runs-on: ubuntu-latest
    environment: build_env
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache qmk toolchain
        uses: actions/cache@v3
        env:
          cache-name: qmk-toolchain
        with:
          path: /home/runner/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}-
          restore-keys: ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install dependencies for qmk build
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3-pip dfu-util dfu-programmer avrdude

      - name: Install qmk using pip
        working-directory: ./qmk_firmware
        run: |
          python3 -m pip install --user qmk
          qmk setup --yes --home .

      - name: Prepare qmk_firmware folder
        run: cp -R keyboards/* qmk_firmware/keyboards/

      - name: Build cockpit-keyboard-pcb firmware
        working-directory: ./qmk_firmware
        env:
          SECRET_1: ${{ secrets.SECRET_1 }}
        run: qmk compile -kb cockpit -km default

      - name: Archive Default
        uses: actions/upload-artifact@v4
        with:
          name: cockpit-keyboard-pcb-default
          path: qmk_firmware/cockpit_default.hex
